# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.1
  hooks:
  - id: pyupgrade
    exclude: .*_pb2.py|.*_pb2_grpc.py
    args: ["--py3-plus"]
- repo: https://github.com/python/black
  rev: 22.1.0
  hooks:
  - id: black
    exclude: .*_pb2.py|.*_pb2_grpc.py
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    exclude: .*_pb2.py|.*_pb2_grpc.py
    additional_dependencies: ['flake8-bugbear==19.3.0']
