target-version = "py311"
line-length = 120
ignore = [
    "E501",
    "E203",
    "E231"
]

[per-file-ignores]
"__init__.py" = ["F401"]

[lint]
select = ["E", "F", "I", "UP", ]

[lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true
